name: Build
on: [push, pull_request]
jobs:
  unit-tests:
    name: unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.16.0
      - name: Install node.js packages
        run: npm install
      - name: Run generator tests
        run: npm test
  integration-tests:
    name: integration tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sample: [maven-angularX, gradle-react]
    timeout-minutes: 40
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v2
        with:
          path: generator-jhipster-es-entity-reindexer
      - uses: actions/setup-node@v2
        with:
          node-version: 14.16.0
      - name: Install node.js packages
        run: npm install
        working-directory: generator-jhipster-es-entity-reindexer
      - name: Link module
        run: npm link
        working-directory: generator-jhipster-es-entity-reindexer
      - name: Create app dir
        run: mkdir app
        working-directory: ${{ github.workspace }}
      - name: Install tools
        run: npm install -g yo
      - name: Install JHipster
        run: npm install -g generator-jhipster
      - name: Prepare temporary directory
        run: |
          cp -r ./test-integration/samples/${{ matrix.sample }} ../app/
          cp -r ./test-integration/samples/.jhipster ../app/${{ matrix.sample }}
        working-directory: generator-jhipster-es-entity-reindexer
      - name: Generate project
        run: |
          jhipster --with-entities --no-insight
          yo jhipster-es-entity-reindexer default --force
      - name: Run backend tests
        run: npm run ci:backend:test
      - name: Run frontend tests
        run: npm run ci:frontend:test
